#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 23 22:22:07 YEKT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.9.3.zip
